export interface TarotCard {
  id: number
  name: string
  nameMM: string
  type: "major" | "minor"
  suit?: "wands" | "cups" | "swords" | "pentacles"
  uprightMeaning: string
  uprightMeaningMM: string
  reversedMeaning: string
  reversedMeaningMM: string
  yesNo: "yes" | "no" | "maybe"
  keywords: string[]
  keywordsMM: string[]
  icon: string
}

export const majorArcana: TarotCard[] = [
  {
    id: 0,
    name: "The Fool",
    nameMM: "အရူး",
    type: "major",
    uprightMeaning:
      "New beginnings, innocence, spontaneity, free spirit. A fresh start awaits you with unlimited potential.",
    uprightMeaningMM: "အစအဦးသစ်များ၊ အပြစ်ကင်းခြင်း၊ လွတ်လပ်သောစိတ်ဓာတ်။ အကန့်အသတ်မရှိသော အလားအလာများဖြင့် အစအဦးသစ်တစ်ခု သင့်ကိုစောင့်နေသည်။",
    reversedMeaning: "Recklessness, risk-taking, holding back. Fear of the unknown prevents progress.",
    reversedMeaningMM: "မဆင်မခြင်၊ စွန့်စားမှု၊ နှောင့်နှေးခြင်း။ မသိသောအရာများကို ကြောက်ရွံ့ခြင်းက တိုးတက်မှုကို တားဆီးနေသည်။",
    yesNo: "yes",
    keywords: ["beginnings", "innocence", "adventure"],
    keywordsMM: ["အစအဦး", "အပြစ်ကင်း", "စွန့်စားခန်း"],
    icon: "🎭",
  },
  {
    id: 1,
    name: "The Magician",
    nameMM: "မှော်ဆရာ",
    type: "major",
    uprightMeaning:
      "Manifestation, resourcefulness, power, inspired action. You have all the tools you need to succeed.",
    uprightMeaningMM: "ထင်ရှားခြင်း၊ ကျွမ်းကျင်မှု၊ စွမ်းအား၊ လှုံ့ဆော်မှုရှိသော လုပ်ရပ်။ အောင်မြင်ရန် လိုအပ်သော ကိရိယာအားလုံး သင့်တွင်ရှိသည်။",
    reversedMeaning: "Manipulation, poor planning, untapped talents. Beware of deception.",
    reversedMeaningMM: "ခြယ်လှယ်ခြင်း၊ အစီအစဉ်ညံ့ခြင်း၊ အသုံးမချရသေးသော အရည်အချင်းများ။ လှည့်ဖြားမှုကို သတိထားပါ။",
    yesNo: "yes",
    keywords: ["power", "skill", "concentration"],
    keywordsMM: ["စွမ်းအား", "ကျွမ်းကျင်မှု", "အာရုံစူးစိုက်မှု"],
    icon: "✨",
  },
  {
    id: 2,
    name: "The High Priestess",
    nameMM: "ဘုန်းတော်ကြီးမ",
    type: "major",
    uprightMeaning: "Intuition, sacred knowledge, divine feminine, the subconscious mind. Trust your inner voice.",
    uprightMeaningMM: "အလိုလိုသိခြင်း၊ မြင့်မြတ်သောအသိပညာ၊ နက်နဲသောစိတ်။ သင့်အတွင်းစိတ်ကို ယုံကြည်ပါ။",
    reversedMeaning: "Secrets, disconnected from intuition, withdrawal. Hidden agendas may be at play.",
    reversedMeaningMM: "လျှို့ဝှက်ချက်များ၊ အလိုလိုသိခြင်းနှင့် ဆက်သွယ်မှုပြတ်ခြင်း။ ဝှက်ထားသော ရည်ရွယ်ချက်များ ရှိနေနိုင်သည်။",
    yesNo: "maybe",
    keywords: ["intuition", "mystery", "wisdom"],
    keywordsMM: ["အလိုလိုသိခြင်း", "နက်နဲမှု", "ပညာ"],
    icon: "🌙",
  },
  {
    id: 3,
    name: "The Empress",
    nameMM: "မိဖုရား",
    type: "major",
    uprightMeaning: "Femininity, beauty, nature, nurturing, abundance. Creative energy flows through you.",
    uprightMeaningMM: "အမျိုးသမီးဆန်မှု၊ အလှ၊ သဘာဝ၊ ပြုစုခြင်း၊ ကြွယ်ဝခြင်း။ ဖန်တီးမှုစွမ်းအင် သင့်တွင် စီးဆင်းနေသည်။",
    reversedMeaning: "Creative block, dependence on others. Neglecting self-care.",
    reversedMeaningMM: "ဖန်တီးမှု ပိတ်ဆို့ခြင်း၊ အခြားသူများအပေါ် မှီခိုခြင်း။ မိမိကိုယ်ကို ဂရုမစိုက်ခြင်း။",
    yesNo: "yes",
    keywords: ["abundance", "nurturing", "fertility"],
    keywordsMM: ["ကြွယ်ဝမှု", "ပြုစုခြင်း", "ဖွံ့ဖြိုးမှု"],
    icon: "👑",
  },
  {
    id: 4,
    name: "The Emperor",
    nameMM: "ဘုရင်",
    type: "major",
    uprightMeaning: "Authority, structure, control, fatherhood. Strong foundation and leadership guide you.",
    uprightMeaningMM: "အာဏာ၊ တည်ဆောက်ပုံ၊ ထိန်းချုပ်မှု၊ ဖခင်ဆန်မှု။ ခိုင်မာသော အခြေခံနှင့် ခေါင်းဆောင်မှုက သင့်ကို လမ်းညွှန်သည်။",
    reversedMeaning: "Domination, excessive control, lack of discipline. Rigidity blocks progress.",
    reversedMeaningMM: "လွှမ်းမိုးခြင်း၊ အလွန်အကျွံ ထိန်းချုပ်ခြင်း၊ စည်းကမ်းမရှိခြင်း။ တောင့်တင်းမှုက တိုးတက်မှုကို တားဆီးနေသည်။",
    yesNo: "yes",
    keywords: ["authority", "structure", "control"],
    keywordsMM: ["အာဏာ", "တည်ဆောက်ပုံ", "ထိန်းချုပ်မှု"],
    icon: "🦁",
  },
  {
    id: 5,
    name: "The Hierophant",
    nameMM: "ဘာသာရေးခေါင်းဆောင်",
    type: "major",
    uprightMeaning: "Spiritual wisdom, religious beliefs, tradition, conformity. Seek guidance from trusted sources.",
    uprightMeaningMM: "ဝိညာဉ်ရေးပညာ၊ ဘာသာရေးယုံကြည်ချက်များ၊ ရိုးရာထုံးတမ်း။ ယုံကြည်ရသော အရင်းအမြစ်များမှ လမ်းညွှန်မှုကို ရှာဖွေပါ။",
    reversedMeaning: "Personal beliefs, freedom, challenging the status quo. Break free from restrictions.",
    reversedMeaningMM: "ကိုယ်ပိုင်ယုံကြည်ချက်များ၊ လွတ်လပ်မှု၊ လက်ရှိအခြေအနေကို စိန်ခေါ်ခြင်း။ ကန့်သတ်ချက်များမှ လွတ်မြောက်ပါ။",
    yesNo: "maybe",
    keywords: ["tradition", "spirituality", "guidance"],
    keywordsMM: ["ရိုးရာ", "ဝိညာဉ်ရေး", "လမ်းညွှန်မှု"],
    icon: "⛪",
  },
  {
    id: 6,
    name: "The Lovers",
    nameMM: "ချစ်သူများ",
    type: "major",
    uprightMeaning: "Love, harmony, relationships, values alignment. A meaningful connection awaits.",
    uprightMeaningMM: "အချစ်၊ သဟဇာတ၊ ဆက်ဆံရေး၊ တန်ဖိုးထားမှုများ ညီညွတ်ခြင်း။ အဓိပ္ပာယ်ရှိသော ဆက်သွယ်မှုတစ်ခု စောင့်နေသည်။",
    reversedMeaning: "Self-love, disharmony, imbalance, misalignment of values. Reflect on your choices.",
    reversedMeaningMM: "မိမိကိုယ်ကို ချစ်ခြင်း၊ သဟဇာတမဖြစ်ခြင်း၊ မမျှတခြင်း။ သင့်ရွေးချယ်မှုများကို ပြန်လည်သုံးသပ်ပါ။",
    yesNo: "yes",
    keywords: ["love", "harmony", "choices"],
    keywordsMM: ["အချစ်", "သဟဇာတ", "ရွေးချယ်မှု"],
    icon: "💕",
  },
  {
    id: 7,
    name: "The Chariot",
    nameMM: "ရထား",
    type: "major",
    uprightMeaning: "Control, willpower, success, action, determination. Victory through focused effort.",
    uprightMeaningMM: "ထိန်းချုပ်မှု၊ စိတ်ဆန္ဒအား၊ အောင်မြင်မှု၊ လုပ်ရပ်၊ ဇွဲလုံ့လ။ အာရုံစူးစိုက်သော ကြိုးပမ်းမှုဖြင့် အောင်ပွဲ။",
    reversedMeaning: "Self-discipline issues, opposition, lack of direction. Reassess your path.",
    reversedMeaningMM: "မိမိကိုယ်ကို စည်းကမ်းပြုခြင်း ပြဿနာများ၊ ဆန့်ကျင်မှု၊ ဦးတည်ချက်မရှိခြင်း။ သင့်လမ်းကို ပြန်လည်သုံးသပ်ပါ။",
    yesNo: "yes",
    keywords: ["victory", "determination", "control"],
    keywordsMM: ["အောင်ပွဲ", "ဇွဲလုံ့လ", "ထိန်းချုပ်မှု"],
    icon: "🏆",
  },
  {
    id: 8,
    name: "Strength",
    nameMM: "ခွန်အား",
    type: "major",
    uprightMeaning: "Strength, courage, persuasion, influence, compassion. Inner power guides you through challenges.",
    uprightMeaningMM: "ခွန်အား၊ သတ္တိ၊ စည်းရုံးနိုင်မှု၊ သက်ရောက်မှု၊ သနားကြင်နာမှု။ စိန်ခေါ်မှုများကို ကျော်ဖြတ်ရန် အတွင်းစွမ်းအားက လမ်းညွှန်သည်။",
    reversedMeaning: "Inner strength, self-doubt, low energy. Find courage within yourself.",
    reversedMeaningMM: "အတွင်းခွန်အား၊ မိမိကိုယ်မိမိ သံသယဖြစ်ခြင်း၊ စွမ်းအင်နည်းခြင်း။ သင့်အတွင်းတွင် သတ္တိကို ရှာဖွေပါ။",
    yesNo: "yes",
    keywords: ["courage", "patience", "compassion"],
    keywordsMM: ["သတ္တိ", "စိတ်ရှည်မှု", "သနားကြင်နာမှု"],
    icon: "🦋",
  },
  {
    id: 9,
    name: "The Hermit",
    nameMM: "ရသေ့",
    type: "major",
    uprightMeaning: "Soul-searching, introspection, being alone, inner guidance. Seek wisdom in solitude.",
    uprightMeaningMM: "စိတ်ဝိညာဉ်ရှာဖွေခြင်း၊ အတွင်းကို ပြန်ကြည့်ခြင်း၊ တစ်ယောက်တည်းနေခြင်း။ တစ်ယောက်တည်းတွင် ပညာကို ရှာဖွေပါ။",
    reversedMeaning: "Isolation, loneliness, withdrawal. Avoid excessive isolation.",
    reversedMeaningMM: "သီးခြားနေခြင်း၊ အထီးကျန်ခြင်း၊ ဆုတ်ခွာခြင်း။ အလွန်အကျွံ သီးခြားနေခြင်းကို ရှောင်ပါ။",
    yesNo: "maybe",
    keywords: ["introspection", "solitude", "guidance"],
    keywordsMM: ["အတွင်းကြည့်ခြင်း", "တစ်ယောက်တည်း", "လမ်းညွှန်မှု"],
    icon: "🏔️",
  },
  {
    id: 10,
    name: "Wheel of Fortune",
    nameMM: "ကံကြမ္မာဘီး",
    type: "major",
    uprightMeaning: "Good luck, karma, life cycles, destiny, turning point. Change is coming in your favor.",
    uprightMeaningMM: "ကံကောင်းခြင်း၊ ကံကြမ္မာ၊ ဘဝသံသရာ၊ ကံဆိုး၊ အပြောင်းအလဲအချိန်။ ပြောင်းလဲမှုသည် သင့်အတွက် ကောင်းသောဘက်သို့ လာနေသည်။",
    reversedMeaning: "Bad luck, resistance to change, breaking cycles. Accept life's natural flow.",
    reversedMeaningMM: "ကံမကောင်းခြင်း၊ ပြောင်းလဲမှုကို ငြင်းဆန်ခြင်း။ ဘဝ၏ သဘာဝစီးဆင်းမှုကို လက်ခံပါ။",
    yesNo: "yes",
    keywords: ["change", "cycles", "fate"],
    keywordsMM: ["ပြောင်းလဲမှု", "သံသရာ", "ကံကြမ္မာ"],
    icon: "🎡",
  },
  {
    id: 11,
    name: "Justice",
    nameMM: "တရားမျှတမှု",
    type: "major",
    uprightMeaning: "Justice, fairness, truth, cause and effect. Fair outcomes await your honest actions.",
    uprightMeaningMM: "တရားမျှတမှု၊ မျှတခြင်း၊ အမှန်တရား၊ အကြောင်းအကျိုး။ သင့်ရိုးသားသော လုပ်ရပ်များအတွက် မျှတသော ရလဒ်များ စောင့်နေသည်။",
    reversedMeaning: "Unfairness, lack of accountability, dishonesty. Seek balance and truth.",
    reversedMeaningMM: "မမျှတခြင်း၊ တာဝန်ခံမှုမရှိခြင်း၊ မရိုးသားခြင်း။ ဟန်ချက်ညီမှုနှင့် အမှန်တရားကို ရှာဖွေပါ။",
    yesNo: "maybe",
    keywords: ["fairness", "truth", "karma"],
    keywordsMM: ["မျှတမှု", "အမှန်တရား", "ကံကြမ္မာ"],
    icon: "⚖️",
  },
  {
    id: 12,
    name: "The Hanged Man",
    nameMM: "ဆွဲချထားသူ",
    type: "major",
    uprightMeaning: "Pause, surrender, letting go, new perspectives. See things from a different angle.",
    uprightMeaningMM: "ခဏရပ်ခြင်း၊ လက်လျှော့ခြင်း၊ လွှတ်ပေးခြင်း၊ အမြင်သစ်များ။ အခြားထောင့်တစ်ခုမှ အရာများကို ကြည့်ပါ။",
    reversedMeaning: "Delays, resistance, stalling. Stop resisting necessary changes.",
    reversedMeaningMM: "နှောင့်နှေးခြင်း၊ ခုခံခြင်း၊ ရပ်တန့်ခြင်း။ လိုအပ်သော ပြောင်းလဲမှုများကို ခုခံခြင်းကို ရပ်ပါ။",
    yesNo: "maybe",
    keywords: ["pause", "surrender", "perspective"],
    keywordsMM: ["ခဏရပ်", "လက်လျှော့", "အမြင်"],
    icon: "🔄",
  },
  {
    id: 13,
    name: "Death",
    nameMM: "သေခြင်း",
    type: "major",
    uprightMeaning: "Endings, change, transformation, transition. End of a chapter, beginning of another.",
    uprightMeaningMM: "အဆုံးသတ်များ၊ ပြောင်းလဲမှု၊ ကူးပြောင်းခြင်း။ အခန်းတစ်ခု၏ အဆုံး၊ နောက်တစ်ခု၏ အစ။",
    reversedMeaning: "Resistance to change, personal transformation. Embrace necessary endings.",
    reversedMeaningMM: "ပြောင်းလဲမှုကို ခုခံခြင်း၊ ကိုယ်ပိုင်ပြောင်းလဲခြင်း။ လိုအပ်သော အဆုံးသတ်များကို လက်ခံပါ။",
    yesNo: "no",
    keywords: ["transformation", "endings", "change"],
    keywordsMM: ["ပြောင်းလဲခြင်း", "အဆုံးသတ်", "ပြောင်းလဲမှု"],
    icon: "🌅",
  },
  {
    id: 14,
    name: "Temperance",
    nameMM: "အသင့်အတင့်",
    type: "major",
    uprightMeaning: "Balance, moderation, patience, purpose. Find harmony in all aspects of life.",
    uprightMeaningMM: "ဟန်ချက်ညီမှု၊ အသင့်အတင့်၊ စိတ်ရှည်မှု၊ ရည်ရွယ်ချက်။ ဘဝ၏ နယ်ပယ်အားလုံးတွင် သဟဇာတကို ရှာဖွေပါ။",
    reversedMeaning: "Imbalance, excess, self-healing. Restore moderation in your life.",
    reversedMeaningMM: "မမျှတခြင်း၊ အလွန်အကျွံ၊ မိမိကိုယ်ကို ကုစားခြင်း။ သင့်ဘဝတွင် အသင့်အတင့်ကို ပြန်လည်ထူထောင်ပါ။",
    yesNo: "yes",
    keywords: ["balance", "patience", "moderation"],
    keywordsMM: ["ဟန်ချက်ညီမှု", "စိတ်ရှည်မှု", "အသင့်အတင့်"],
    icon: "⚗️",
  },
  {
    id: 15,
    name: "The Devil",
    nameMM: "နတ်ဆိုး",
    type: "major",
    uprightMeaning: "Shadow self, attachment, addiction, restriction. Recognize what binds you.",
    uprightMeaningMM: "အမှောင်ဘက်မှကိုယ်၊ စွဲလမ်းမှု၊ ကန့်သတ်မှု။ သင့်ကို ချုပ်နှောင်ထားသည်ကို အသိအမှတ်ပြုပါ။",
    reversedMeaning: "Releasing limiting beliefs, exploring dark thoughts. Break free from chains.",
    reversedMeaningMM: "ကန့်သတ်သော ယုံကြည်ချက်များကို လွှတ်ခြင်း။ ချိတ်ဆက်များမှ လွတ်မြောက်ပါ။",
    yesNo: "no",
    keywords: ["bondage", "addiction", "materialism"],
    keywordsMM: ["ချုပ်နှောင်မှု", "စွဲလမ်းမှု", "ရုပ်ဝါဒ"],
    icon: "⛓️",
  },
  {
    id: 16,
    name: "The Tower",
    nameMM: "မျှော်စင်",
    type: "major",
    uprightMeaning: "Sudden change, upheaval, chaos, revelation, awakening. Destruction leads to rebuilding.",
    uprightMeaningMM: "ရုတ်တရက်ပြောင်းလဲမှု၊ ပြိုကွဲမှု၊ ရှုပ်ထွေးမှု၊ ဖော်ထုတ်မှု။ ဖျက်ဆီးခြင်းက ပြန်လည်တည်ဆောက်ခြင်းသို့ ဦးတည်သည်။",
    reversedMeaning: "Personal transformation, fear of change. Embrace necessary upheaval.",
    reversedMeaningMM: "ကိုယ်ပိုင်ပြောင်းလဲခြင်း၊ ပြောင်းလဲမှုကို ကြောက်ခြင်း။ လိုအပ်သော ပြိုကွဲမှုကို လက်ခံပါ။",
    yesNo: "no",
    keywords: ["upheaval", "revelation", "change"],
    keywordsMM: ["ပြိုကွဲမှု", "ဖော်ထုတ်မှု", "ပြောင်းလဲမှု"],
    icon: "⚡",
  },
  {
    id: 17,
    name: "The Star",
    nameMM: "ကြယ်",
    type: "major",
    uprightMeaning: "Hope, faith, purpose, renewal, spirituality. Bright future awaits.",
    uprightMeaningMM: "မျှော်လင့်ချက်၊ ယုံကြည်မှု၊ ရည်ရွယ်ချက်၊ အသစ်ပြန်ဖြစ်ခြင်း။ တောက်ပသော အနာဂတ် စောင့်နေသည်။",
    reversedMeaning: "Lack of faith, despair, self-trust issues. Reconnect with hope.",
    reversedMeaningMM: "ယုံကြည်မှုမရှိခြင်း၊ စိတ်ပျက်ခြင်း။ မျှော်လင့်ချက်နှင့် ပြန်လည်ဆက်သွယ်ပါ။",
    yesNo: "yes",
    keywords: ["hope", "faith", "renewal"],
    keywordsMM: ["မျှော်လင့်ချက်", "ယုံကြည်မှု", "အသစ်ပြန်ဖြစ်ခြင်း"],
    icon: "⭐",
  },
  {
    id: 18,
    name: "The Moon",
    nameMM: "လ",
    type: "major",
    uprightMeaning: "Illusion, fear, anxiety, subconscious, intuition. Trust your instincts through uncertainty.",
    uprightMeaningMM: "မှားယွင်းခြင်း၊ ကြောက်ရွံ့ခြင်း၊ စိုးရိမ်ခြင်း၊ အလိုလိုသိခြင်း။ မသေချာမှုတွင် သင့်စိတ်ကို ယုံကြည်ပါ။",
    reversedMeaning: "Release of fear, repressed emotion. Face hidden truths.",
    reversedMeaningMM: "ကြောက်ရွံ့မှုကို လွှတ်ခြင်း၊ ဖိနှိပ်ထားသော ခံစားချက်။ ဝှက်ထားသော အမှန်တရားများကို ရင်ဆိုင်ပါ။",
    yesNo: "no",
    keywords: ["intuition", "illusion", "fear"],
    keywordsMM: ["အလိုလိုသိခြင်း", "မှားယွင်းခြင်း", "ကြောက်ရွံ့ခြင်း"],
    icon: "🌙",
  },
  {
    id: 19,
    name: "The Sun",
    nameMM: "နေ",
    type: "major",
    uprightMeaning: "Positivity, fun, warmth, success, vitality. Joy and abundance shine upon you.",
    uprightMeaningMM: "အပြုသဘော၊ ပျော်ရွှင်မှု၊ နွေးထွေးမှု၊ အောင်မြင်မှု။ ဝမ်းမြောက်ခြင်းနှင့် ကြွယ်ဝခြင်း သင့်အပေါ် တောက်ပနေသည်။",
    reversedMeaning: "Inner child, feeling down, overly optimistic. Find your inner light.",
    reversedMeaningMM: "အတွင်းကလေး၊ စိတ်ဓာတ်ကျခြင်း။ သင့်အတွင်းအလင်းကို ရှာဖွေပါ။",
    yesNo: "yes",
    keywords: ["joy", "success", "positivity"],
    keywordsMM: ["ဝမ်းမြောက်ခြင်း", "အောင်မြင်မှု", "အပြုသဘော"],
    icon: "☀️",
  },
  {
    id: 20,
    name: "Judgement",
    nameMM: "တရားစီရင်ခြင်း",
    type: "major",
    uprightMeaning: "Judgement, rebirth, inner calling, absolution. Answer your higher calling.",
    uprightMeaningMM: "တရားစီရင်ခြင်း၊ ပြန်လည်မွေးဖွားခြင်း၊ အတွင်းခေါ်သံ။ သင့်မြင့်မြတ်သော ခေါ်သံကို ဖြေကြားပါ။",
    reversedMeaning: "Self-doubt, inner critic. Release self-judgement.",
    reversedMeaningMM: "မိမိကိုယ်မိမိ သံသယဖြစ်ခြင်း၊ အတွင်းဝေဖန်မှု။ မိမိကိုယ်မိမိ တရားစီရင်ခြင်းကို လွှတ်ပါ။",
    yesNo: "yes",
    keywords: ["rebirth", "calling", "judgement"],
    keywordsMM: ["ပြန်လည်မွေးဖွားခြင်း", "ခေါ်သံ", "တရားစီရင်ခြင်း"],
    icon: "📯",
  },
  {
    id: 21,
    name: "The World",
    nameMM: "ကမ္ဘာ",
    type: "major",
    uprightMeaning: "Completion, integration, accomplishment, travel. A cycle completes successfully.",
    uprightMeaningMM: "ပြီးမြောက်ခြင်း၊ ပေါင်းစည်းခြင်း၊ အောင်မြင်မှု။ သံသရာတစ်ခု အောင်မြင်စွာ ပြီးဆုံးသည်။",
    reversedMeaning: "Seeking personal closure, short-cuts. Complete what you started.",
    reversedMeaningMM: "ကိုယ်ပိုင်ပြီးဆုံးမှုကို ရှာဖွေခြင်း၊ ဖြတ်လမ်းများ။ သင်စတင်ခဲ့သည်ကို ပြီးမြောက်အောင်လုပ်ပါ။",
    yesNo: "yes",
    keywords: ["completion", "accomplishment", "travel"],
    keywordsMM: ["ပြီးမြောက်ခြင်း", "အောင်မြင်မှု", "ခရီးသွားခြင်း"],
    icon: "🌍",
  },
]

export const minorArcana: TarotCard[] = [
  // Wands
  {
    id: 22,
    name: "Ace of Wands",
    nameMM: "တုတ်တံ၏ တစ်",
    type: "minor",
    suit: "wands",
    uprightMeaning: "Inspiration, new opportunities, growth, potential. Creative spark ignites.",
    uprightMeaningMM: "လှုံ့ဆော်မှု၊ အခွင့်အလမ်းသစ်များ၊ တိုးတက်မှု၊ အလားအလာ။ ဖန်တီးမှု မီးပွားထွက်သည်။",
    reversedMeaning: "Lack of energy, delays, weighed down. Creative blocks.",
    reversedMeaningMM: "စွမ်းအင်မရှိခြင်း၊ နှောင့်နှေးခြင်း။ ဖန်တီးမှု ပိတ်ဆို့မှုများ။",
    yesNo: "yes",
    keywords: ["inspiration", "potential", "creation"],
    keywordsMM: ["လှုံ့ဆော်မှု", "အလားအလာ", "ဖန်တီးခြင်း"],
    icon: "🔥",
  },
  {
    id: 23,
    name: "Two of Wands",
    nameMM: "တုတ်တံ၏ နှစ်",
    type: "minor",
    suit: "wands",
    uprightMeaning: "Future planning, progress, decisions, discovery. Plan your next move.",
    uprightMeaningMM: "အနာဂတ်အစီအစဉ်၊ တိုးတက်မှု၊ ဆုံးဖြတ်ချက်များ။ နောက်ထပ်လှုပ်ရှားမှုကို စီစဉ်ပါ။",
    reversedMeaning: "Personal goals, inner alignment, fear of unknown.",
    reversedMeaningMM: "ကိုယ်ပိုင်ရည်မှန်းချက်များ၊ အတွင်းညီညွတ်မှု၊ မသိသောအရာကို ကြောက်ခြင်း။",
    yesNo: "yes",
    keywords: ["planning", "progress", "decisions"],
    keywordsMM: ["စီစဉ်ခြင်း", "တိုးတက်မှု", "ဆုံးဖြတ်ချက်"],
    icon: "🗺️",
  },
  {
    id: 24,
    name: "Three of Wands",
    nameMM: "တုတ်တံ၏ သုံး",
    type: "minor",
    suit: "wands",
    uprightMeaning: "Progress, expansion, foresight, overseas opportunities. Ventures succeed.",
    uprightMeaningMM: "တိုးတက်မှု၊ ချဲ့ထွင်မှု၊ ကြိုတင်မြင်ခြင်း။ လုပ်ငန်းများ အောင်မြင်သည်။",
    reversedMeaning: "Playing small, lack of foresight, delays.",
    reversedMeaningMM: "အသေးအမွှားကစားခြင်း၊ ကြိုတင်မြင်မှုမရှိခြင်း၊ နှောင့်နှေးခြင်း။",
    yesNo: "yes",
    keywords: ["expansion", "foresight", "progress"],
    keywordsMM: ["ချဲ့ထွင်မှု", "ကြိုတင်မြင်ခြင်း", "တိုးတက်မှု"],
    icon: "🚀",
  },
  // Cups
  {
    id: 36,
    name: "Ace of Cups",
    nameMM: "ဖလား၏ တစ်",
    type: "minor",
    suit: "cups",
    uprightMeaning: "Love, new relationships, compassion, creativity. Emotional fulfillment awaits.",
    uprightMeaningMM: "အချစ်၊ ဆက်ဆံရေးသစ်များ၊ သနားကြင်နာမှု၊ ဖန်တီးမှု။ ခံစားချက်ပြည့်ဝမှု စောင့်နေသည်။",
    reversedMeaning: "Self-love, intuition, repressed emotions.",
    reversedMeaningMM: "မိမိကိုယ်ကို ချစ်ခြင်း၊ အလိုလိုသိခြင်း၊ ဖိနှိပ်ထားသော ခံစားချက်များ။",
    yesNo: "yes",
    keywords: ["love", "emotion", "intuition"],
    keywordsMM: ["အချစ်", "ခံစားချက်", "အလိုလိုသိခြင်း"],
    icon: "💧",
  },
  {
    id: 37,
    name: "Two of Cups",
    nameMM: "ဖလား၏ နှစ်",
    type: "minor",
    suit: "cups",
    uprightMeaning: "Unified love, partnership, mutual attraction. Strong bonds form.",
    uprightMeaningMM: "စည်းလုံးသောအချစ်၊ မိတ်ဖက်၊ အပြန်အလှန်ဆွဲဆောင်မှု။ ခိုင်မာသော ချိတ်ဆက်မှုများ ဖြစ်ပေါ်သည်။",
    reversedMeaning: "Self-love, break-ups, disharmony.",
    reversedMeaningMM: "မိမိကိုယ်ကို ချစ်ခြင်း၊ ကွဲကွာခြင်း၊ သဟဇာတမဖြစ်ခြင်း။",
    yesNo: "yes",
    keywords: ["partnership", "love", "attraction"],
    keywordsMM: ["မိတ်ဖက်", "အချစ်", "ဆွဲဆောင်မှု"],
    icon: "💑",
  },
  {
    id: 38,
    name: "Three of Cups",
    nameMM: "ဖလား၏ သုံး",
    type: "minor",
    suit: "cups",
    uprightMeaning: "Celebration, friendship, creativity, collaborations. Joyful gatherings.",
    uprightMeaningMM: "ပွဲချင်းဆိုင်ခြင်း၊ မိတ်ဆွေရေး၊ ဖန်တီးမှု၊ ပူးပေါင်းဆောင်ရွက်မှုများ။ ပျော်ရွှင်သော စုဝေးမှုများ။",
    reversedMeaning: "Independence, alone time, hard times.",
    reversedMeaningMM: "လွတ်လပ်မှု၊ တစ်ယောက်တည်းအချိန်၊ ခက်ခဲသောအချိန်များ။",
    yesNo: "yes",
    keywords: ["celebration", "friendship", "joy"],
    keywordsMM: ["ပွဲချင်းဆိုင်", "မိတ်ဆွေရေး", "ပျော်ရွှင်မှု"],
    icon: "🥂",
  },
  // Swords
  {
    id: 50,
    name: "Ace of Swords",
    nameMM: "ဓား၏ တစ်",
    type: "minor",
    suit: "swords",
    uprightMeaning: "Breakthrough, clarity, sharp mind, success. Mental clarity achieved.",
    uprightMeaningMM: "ထိုးဖောက်မှု၊ ရှင်းလင်းမှု၊ ထက်မြက်သောစိတ်၊ အောင်မြင်မှု။ စိတ်ပိုင်းဆိုင်ရာ ရှင်းလင်းမှု ရရှိသည်။",
    reversedMeaning: "Inner clarity, re-thinking, clouded judgement.",
    reversedMeaningMM: "အတွင်းရှင်းလင်းမှု၊ ပြန်လည်စဉ်းစားခြင်း၊ တိမ်ထူနေသော ဆုံးဖြတ်ချက်။",
    yesNo: "yes",
    keywords: ["clarity", "truth", "breakthrough"],
    keywordsMM: ["ရှင်းလင်းမှု", "အမှန်တရား", "ထိုးဖောက်မှု"],
    icon: "⚔️",
  },
  {
    id: 51,
    name: "Two of Swords",
    nameMM: "ဓား၏ နှစ်",
    type: "minor",
    suit: "swords",
    uprightMeaning: "Difficult decisions, weighing options, stalemate. Balance opposing forces.",
    uprightMeaningMM: "ခက်ခဲသော ဆုံးဖြတ်ချက်များ၊ ရွေးချယ်စရာများ ချိန်ခွင်ခြင်း။ ဆန့်ကျင်ဘက်အင်အားများကို ဟန်ချက်ညီအောင်လုပ်ပါ။",
    reversedMeaning: "Indecision, confusion, information overload.",
    reversedMeaningMM: "ဆုံးဖြတ်မပြတ်ခြင်း၊ ရှုပ်ထွေးမှု၊ သတင်းအချက်အလက် လွန်ကဲခြင်း။",
    yesNo: "maybe",
    keywords: ["decisions", "balance", "stalemate"],
    keywordsMM: ["ဆုံးဖြတ်ချက်", "ဟန်ချက်ညီမှု", "ရပ်တန့်မှု"],
    icon: "🤔",
  },
  {
    id: 52,
    name: "Three of Swords",
    nameMM: "ဓား၏ သုံး",
    type: "minor",
    suit: "swords",
    uprightMeaning: "Heartbreak, emotional pain, sorrow, grief. Healing through pain.",
    uprightMeaningMM: "နှလုံးကွဲခြင်း၊ ခံစားချက်ပိုင်းဆိုင်ရာ နာကျင်မှု၊ ဝမ်းနည်းမှု။ နာကျင်မှုမှတဆင့် ကုသခြင်း။",
    reversedMeaning: "Moving on, releasing pain, forgiveness.",
    reversedMeaningMM: "ရှေ့ဆက်ခြင်း၊ နာကျင်မှုကို လွှတ်ခြင်း၊ ခွင့်လွှတ်ခြင်း။",
    yesNo: "no",
    keywords: ["heartbreak", "sorrow", "pain"],
    keywordsMM: ["နှလုံးကွဲခြင်း", "ဝမ်းနည်းမှု", "နာကျင်မှု"],
    icon: "💔",
  },
  // Pentacles
  {
    id: 64,
    name: "Ace of Pentacles",
    nameMM: "ပဉ္စဂံ၏ တစ်",
    type: "minor",
    suit: "pentacles",
    uprightMeaning: "New financial opportunity, manifestation, abundance. Material success begins.",
    uprightMeaningMM: "ငွေကြေးအခွင့်အလမ်းသစ်၊ ထင်ရှားခြင်း၊ ကြွယ်ဝခြင်း။ ရုပ်ဝတ္ထုအောင်မြင်မှု စတင်သည်။",
    reversedMeaning: "Lost opportunity, lack of planning.",
    reversedMeaningMM: "ဆုံးရှုံးသော အခွင့်အလမ်း၊ အစီအစဉ်မရှိခြင်း။",
    yesNo: "yes",
    keywords: ["opportunity", "prosperity", "new venture"],
    keywordsMM: ["အခွင့်အလမ်း", "ချမ်းသာမှု", "လုပ်ငန်းသစ်"],
    icon: "💰",
  },
  {
    id: 65,
    name: "Two of Pentacles",
    nameMM: "ပဉ္စဂံ၏ နှစ်",
    type: "minor",
    suit: "pentacles",
    uprightMeaning: "Multiple priorities, time management, prioritization. Balance your resources.",
    uprightMeaningMM: "ဦးစားပေးအများအပြား၊ အချိန်စီမံခန့်ခွဲမှု။ သင့်အရင်းအမြစ်များကို ဟန်ချက်ညီအောင်လုပ်ပါ။",
    reversedMeaning: "Over-committed, disorganization.",
    reversedMeaningMM: "အလွန်အကျွံကတိပေးခြင်း၊ စနစ်မကျခြင်း။",
    yesNo: "maybe",
    keywords: ["balance", "priorities", "adaptability"],
    keywordsMM: ["ဟန်ချက်ညီမှု", "ဦးစားပေးမှု", "လိုက်လျောညီထွေမှု"],
    icon: "⚖️",
  },
  {
    id: 66,
    name: "Three of Pentacles",
    nameMM: "ပဉ္စဂံ၏ သုံး",
    type: "minor",
    suit: "pentacles",
    uprightMeaning: "Teamwork, collaboration, learning, implementation. Skilled work pays off.",
    uprightMeaningMM: "အသင်းအဖွဲ့လုပ်ငန်း၊ ပူးပေါင်းဆောင်ရွက်မှု၊ သင်ယူခြင်း။ ကျွမ်းကျင်သော အလုပ်က အကျိုးရလဒ်ပေးသည်။",
    reversedMeaning: "Disharmony, misalignment, working alone.",
    reversedMeaningMM: "သဟဇာတမဖြစ်ခြင်း၊ ညီညွတ်မှုမရှိခြင်း၊ တစ်ယောက်တည်း အလုပ်လုပ်ခြင်း။",
    yesNo: "yes",
    keywords: ["teamwork", "skill", "collaboration"],
    keywordsMM: ["အသင်းအဖွဲ့", "ကျွမ်းကျင်မှု", "ပူးပေါင်းဆောင်ရွက်မှု"],
    icon: "🏗️",
  },
]

export const allCards = [...majorArcana, ...minorArcana]

export interface ZodiacSign {
  name: string
  nameMM: string
  symbol: string
  element: string
  dateRange: string
  love: string
  loveMM: string
  education: string
  educationMM: string
  personal: string
  personalMM: string
}

export const zodiacSigns: ZodiacSign[] = [
  {
    name: "Aries",
    nameMM: "မိဿရာသီ",
    symbol: "♈",
    element: "Fire",
    dateRange: "Mar 21 - Apr 19",
    love: "Passionate connections await. Your bold energy attracts admirers. Express your feelings openly.",
    loveMM: "စိတ်အားထက်သံသော ဆက်သွယ်မှုများ စောင့်နေသည်။ သင့်ရဲရင့်သော စွမ်းအင်က ချစ်မြတ်နိုးသူများကို ဆွဲဆောင်သည်။",
    education: "Quick learning abilities shine. Take initiative in studies. Leadership roles suit you.",
    educationMM: "မြန်ဆန်သော သင်ယူနိုင်စွမ်း တောက်ပနေသည်။ ပညာရေးတွင် ဦးဆောင်မှုပြုပါ။",
    personal: "Self-confidence grows. New beginnings favor you. Trust your instincts.",
    personalMM: "မိမိကိုယ်မိမိ ယုံကြည်မှု တိုးပွားလာသည်။ အစအဦးသစ်များ သင့်ကို ထောက်ခံသည်။",
  },
  {
    name: "Taurus",
    nameMM: "ပြိဿရာသီ",
    symbol: "♉",
    element: "Earth",
    dateRange: "Apr 20 - May 20",
    love: "Stable and nurturing love blooms. Patience in relationships pays off. Sensual pleasures await.",
    loveMM: "တည်ငြိမ်ပြီး ပြုစုသော အချစ် ပွင့်ဖူးလာသည်။ ဆက်ဆံရေးတွင် စိတ်ရှည်မှုက အကျိုးပေးသည်။",
    education: "Steady progress in learning. Practical subjects suit you. Persistence leads to mastery.",
    educationMM: "သင်ယူမှုတွင် တည်ငြိမ်သော တိုးတက်မှု။ လက်တွေ့ဘာသာရပ်များ သင့်နှင့်ကိုက်ညီသည်။",
    personal: "Financial stability improves. Comfort and security are priorities. Enjoy life's pleasures.",
    personalMM: "ငွေကြေးတည်ငြိမ်မှု တိုးတက်လာသည်။ သက်သာမှုနှင့် လုံခြုံမှုသည် ဦးစားပေးဖြစ်သည်။",
  },
  {
    name: "Gemini",
    nameMM: "မေထုန်ရာသီ",
    symbol: "♊",
    element: "Air",
    dateRange: "May 21 - Jun 20",
    love: "Communication opens hearts. Variety in romance excites you. Express your dual nature.",
    loveMM: "ဆက်သွယ်ရေးက နှလုံးသားများကို ဖွင့်ပေးသည်။ အချစ်ရေးတွင် မျိုးစုံမှုက သင့်ကို စိတ်လှုပ်ရှားစေသည်။",
    education: "Multiple interests flourish. Quick wit aids learning. Networking brings opportunities.",
    educationMM: "စိတ်ဝင်စားမှု အများအပြား ဖွံ့ဖြိုးလာသည်။ မြန်ဆန်သော ဉာဏ်က သင်ယူမှုကို ကူညီသည်။",
    personal: "Adaptability is your strength. Social connections expand. Embrace your curious nature.",
    personalMM: "လိုက်လျောညီထွေမှုသည် သင့်အင်အားဖြစ်သည်။ လူမှုဆက်သွယ်မှုများ ချဲ့ထွင်လာသည်။",
  },
  {
    name: "Cancer",
    nameMM: "ကရကဋ်ရာသီ",
    symbol: "♋",
    element: "Water",
    dateRange: "Jun 21 - Jul 22",
    love: "Deep emotional bonds form. Family-oriented love grows. Nurturing relationships thrive.",
    loveMM: "နက်နဲသော ခံစားချက်ချိတ်ဆက်မှုများ ဖြစ်ပေါ်လာသည်။ မိသားစုကို ဦးစားပေးသော အချစ် တိုးပွားလာသည်။",
    education: "Intuitive learning excels. Creative subjects attract. Home-based study suits you.",
    educationMM: "အလိုလိုသိသော သင်ယူမှု ထူးချွန်သည်။ ဖန်တီးမှုဆိုင်ရာ ဘာသာရပ်များ ဆွဲဆောင်သည်။",
    personal: "Emotional intelligence grows. Home life brings comfort. Trust your intuition.",
    personalMM: "ခံစားချက်ဆိုင်ရာ ဉာဏ်ရည် တိုးပွားလာသည်။ အိမ်ဘဝက သက်သာမှုပေးသည်။",
  },
  {
    name: "Leo",
    nameMM: "သိဟ်ရာသီ",
    symbol: "♌",
    element: "Fire",
    dateRange: "Jul 23 - Aug 22",
    love: "Romance and passion ignite. Your charm attracts admirers. Express love boldly.",
    loveMM: "ရိုမန်တစ်နှင့် စိတ်အားထက်သံမှု မီးလောင်လာသည်။ သင့်ဆွဲဆောင်မှုက ချစ်မြတ်နိုးသူများကို ဆွဲဆောင်သည်။",
    education: "Creative talents shine. Leadership in studies suits you. Recognition comes naturally.",
    educationMM: "ဖန်တီးမှုစွမ်းရည်များ တောက်ပလာသည်။ ပညာရေးတွင် ခေါင်းဆောင်မှု သင့်နှင့်ကိုက်ညီသည်။",
    personal: "Self-expression flourishes. Confidence attracts success. Shine your inner light.",
    personalMM: "မိမိကိုယ်မိမိ ဖော်ပြမှု ဖွံ့ဖြိုးလာသည်။ ယုံကြည်မှုက အောင်မြင်မှုကို ဆွဲဆောင်သည်။",
  },
  {
    name: "Virgo",
    nameMM: "ကန်ရာသီ",
    symbol: "♍",
    element: "Earth",
    dateRange: "Aug 23 - Sep 22",
    love: "Practical love grows. Attention to detail strengthens bonds. Service to partner matters.",
    loveMM: "လက်တွေ့ကျသော အချစ် တိုးပွားလာသည်။ အသေးစိတ်ဂရုစိုက်မှုက ချိတ်ဆက်မှုများကို ခိုင်မာစေသည်။",
    education: "Analytical skills excel. Detail-oriented study pays off. Health sciences attract.",
    educationMM: "ခွဲခြမ်းစိတ်ဖြာမှု ကျွမ်းကျင်မှုများ ထူးချွန်သည်။ အသေးစိတ်ဦးစားပေး လေ့လာမှုက အကျိုးရလဒ်ပေးသည်။",
    personal: "Self-improvement thrives. Health and wellness matter. Organization brings peace.",
    personalMM: "မိမိကိုယ်မိမိ တိုးတက်မှု ဖွံ့ဖြိုးလာသည်။ ကျန်းမာရေးနှင့် သာယာမှု အရေးကြီးသည်။",
  },
  {
    name: "Libra",
    nameMM: "တူရာသီ",
    symbol: "♎",
    element: "Air",
    dateRange: "Sep 23 - Oct 22",
    love: "Harmony in relationships blooms. Partnership energy is strong. Balance gives and takes.",
    loveMM: "ဆက်ဆံရေးတွင် သဟဇာတ ပွင့်ဖူးလာသည်။ မိတ်ဖက်စွမ်းအင် ခိုင်မာသည်။",
    education: "Arts and aesthetics attract. Balanced study approach works. Collaborative learning thrives.",
    educationMM: "အနုပညာနှင့် အလှပညာများ ဆွဲဆောင်သည်။ ဟန်ချက်ညီသော လေ့လာမှုနည်းလမ်း အလုပ်ဖြစ်သည်။",
    personal: "Diplomacy is your strength. Social life flourishes. Seek beauty in all things.",
    personalMM: "သံတမန်နည်းလမ်းသည် သင့်အင်အားဖြစ်သည်။ လူမှုဘဝ ဖွံ့ဖြိုးလာသည်။",
  },
  {
    name: "Scorpio",
    nameMM: "ဗြိစ္ဆာရာသီ",
    symbol: "♏",
    element: "Water",
    dateRange: "Oct 23 - Nov 21",
    love: "Intense connections form. Transformation in love occurs. Deep loyalty defines bonds.",
    loveMM: "ပြင်းထန်သော ဆက်သွယ်မှုများ ဖြစ်ပေါ်လာသည်။ အချစ်ရေးတွင် ပြောင်းလဲမှု ဖြစ်ပေါ်သည်။",
    education: "Research and investigation excel. Psychology and mysteries attract. Deep learning succeeds.",
    educationMM: "သုတေသနနှင့် စုံစမ်းစစ်ဆေးမှု ထူးချွန်သည်။ စိတ်ပညာနှင့် နက်နဲသော အရာများ ဆွဲဆောင်သည်။",
    personal: "Personal power grows. Transformation is possible. Trust your intuitive depth.",
    personalMM: "ကိုယ်ပိုင်စွမ်းအား တိုးပွားလာသည်။ ပြောင်းလဲမှု ဖြစ်နိုင်သည်။",
  },
  {
    name: "Sagittarius",
    nameMM: "ဓနုရာသီ",
    symbol: "♐",
    element: "Fire",
    dateRange: "Nov 22 - Dec 21",
    love: "Adventurous love beckons. Freedom in relationships matters. Philosophical bonds form.",
    loveMM: "စွန့်စားခန်းအချစ် ခေါ်ဆိုနေသည်။ ဆက်ဆံရေးတွင် လွတ်လပ်မှု အရေးကြီးသည်။",
    education: "Higher learning attracts. Philosophy and travel expand mind. Teaching abilities shine.",
    educationMM: "အဆင့်မြင့်ပညာရေး ဆွဲဆောင်သည်။ ဒဿနိကဗေဒနှင့် ခရီးသွားခြင်းက စိတ်ကို ချဲ့ထွင်ပေးသည်။",
    personal: "Optimism guides you. Adventure awaits. Expand your horizons fearlessly.",
    personalMM: "အပြုသဘောက သင့်ကို လမ်းညွှန်သည်။ စွန့်စားခန်း စောင့်နေသည်။",
  },
  {
    name: "Capricorn",
    nameMM: "မကာရရာသီ",
    symbol: "♑",
    element: "Earth",
    dateRange: "Dec 22 - Jan 19",
    love: "Committed love grows. Long-term relationships thrive. Traditional values matter.",
    loveMM: "ကတိကဝတ်ရှိသော အချစ် တိုးပွားလာသည်။ ရေရှည်ဆက်ဆံရေးများ ဖွံ့ဖြိုးလာသည်။",
    education: "Ambitious study goals succeed. Business and management attract. Discipline leads to achievement.",
    educationMM: "ရည်မှန်းချက်ကြီးသော ပညာရည်မှန်းချက်များ အောင်မြင်သည်။ စီးပွားရေးနှင့် စီမံခန့်ခွဲမှု ဆွဲဆောင်သည်။",
    personal: "Career ambitions advance. Hard work pays off. Build lasting foundations.",
    personalMM: "အလုပ်ရည်မှန်းချက်များ တိုးတက်လာသည်။ ကြိုးစားအားထုတ်မှုက အကျိုးပေးသည်။",
  },
  {
    name: "Aquarius",
    nameMM: "ကုမ္ဘရာသီ",
    symbol: "♒",
    element: "Air",
    dateRange: "Jan 20 - Feb 18",
    love: "Unconventional love attracts. Friendship-based romance grows. Intellectual bonds matter.",
    loveMM: "ထူးခြားသော အချစ် ဆွဲဆောင်သည်။ မိတ်ဆွေရေးအခြေခံ ရိုမန်တစ် တိုးပွားလာသည်။",
    education: "Innovation in learning excels. Technology and science attract. Humanitarian studies suit you.",
    educationMM: "သင်ယူမှုတွင် ဆန်းသစ်တီထွင်မှု ထူးချွန်သည်။ နည်းပညာနှင့် သိပ္ပံ ဆွဲဆောင်သည်။",
    personal: "Individuality shines. Future-focused thinking helps. Embrace your uniqueness.",
    personalMM: "ထူးခြားမှု တောက်ပလာသည်။ အနာဂတ်ကို ဦးစားပေးသော တွေးခေါ်မှုက ကူညီသည်။",
  },
  {
    name: "Pisces",
    nameMM: "မိန်ရာသီ",
    symbol: "♓",
    element: "Water",
    dateRange: "Feb 19 - Mar 20",
    love: "Romantic dreams come true. Spiritual love deepens. Compassionate connections form.",
    loveMM: "ရိုမန်တစ်အိပ်မက်များ အကောင်အထည်ပေါ်လာသည်။ ဝိညာဉ်ရေးအချစ် နက်ရှိုင်းလာသည်။",
    education: "Creative arts excel. Intuitive learning works. Spiritual studies attract.",
    educationMM: "ဖန်တီးမှုအနုပညာများ ထူးချွန်သည်။ အလိုလိုသိသော သင်ယူမှု အလုပ်ဖြစ်သည်။",
    personal: "Intuition guides strongly. Dreams hold meaning. Embrace your spiritual gifts.",
    personalMM: "အလိုလိုသိခြင်းက ခိုင်မာစွာ လမ်းညွှန်သည်။ အိပ်မက်များ အဓိပ္ပာယ်ရှိသည်။",
  },
]
